version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app  # Sinkronisasi kode dari host ke kontainer
    environment:
      FLASK_ENV: development
    ports:
      - "8000:8000"
    depends_on:
      - db
